-- Productos extraidos de L1.19.9 (1).pdf.
-- Ejecutar en Supabase SQL Editor despues de supabase/schema.sql.

with source (
  code,
  name,
  description,
  brand,
  category_slug,
  presentation,
  unit,
  pack_quantity,
  price,
  featured,
  nocera_product,
  image_path
) as (
values
  ('300S', 'SEISEME JABON EN PAM 300GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1550.00, false, false, null),
  ('041SV', 'SIDRA DEL VALLE DE 720 CCX6U.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 11500.00, false, false, null),
  ('011AC', 'AGUA CIMES 600 CC X 12', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4100.00, false, false, null),
  ('045C', 'SOL PAMPEANO CODO X 500 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 800.00, false, false, null),
  ('011DCC', 'AGUA DIBU COMUN 12 X 500', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6960.00, false, false, null),
  ('039ABD', 'SOL PAMPEANO TALLARIN X500GRS[20U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 850.00, false, false, null),
  ('011DCP', 'AGUA DIBU PREMIUN 12 X 500', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8650.00, false, false, null),
  ('022SMM', 'SOLANDES MALBEC MALBEC 6 X 750', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1500.00, false, false, null),
  ('039A', 'ALARIS MALBEC 750 ML', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3600.00, false, false, null),
  ('023SBG', 'SPIRITS BLUE GIN X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8000.00, false, false, null),
  ('047AMC', 'ARROZ MAROLIO L/F 500 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 700.00, false, false, null),
  ('023SL', 'SPIRITS LONDON DRY GIN X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8000.00, false, false, null),
  ('047AM', 'ARROZ MAROLIO L/F 1KG', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1270.00, false, false, null),
  ('003CX', 'SPRITE 500CC X 12U.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 17000.00, false, false, null),
  ('303', 'ARROZ MONEDA LARGO FINO X500GRS[10', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 600.00, false, false, null),
  ('001TXXL', 'TABLA 25X35 XXL X 20U.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3870.00, false, false, null),
  ('012A', 'AVENA 1KG.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3300.00, false, false, null),
  ('001TAM', 'TAZON AMANECER 370CC X UNIDAD[CAJA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1410.00, false, false, null),
  ('330F', 'AZUCAR IMPERIAL COMUN X1KG [10U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1250.00, false, false, null),
  ('014CL', 'TE TARAGUI SIN ENSOBRAR X25[X10]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 850.00, false, false, null),
  ('300LM', 'AZUCAR LA MUÑECA X 1K', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1130.00, false, false, null),
  ('001VO100', 'VASO OSLO 100CC X UNIDAD [CAJAX72U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 700.00, false, false, null),
  ('320L', 'AZUCAR LEDESMA 1 KG', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1440.00, false, false, null),
  ('001VO150', 'VASO OSLO 150CC X UNIDAD [CAJA X72', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 820.00, false, false, null),
  ('011DB6', 'BIDON AGUA DIBU 6.5 LT', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1700.00, false, false, null),
  ('001VO350', 'VASO OSLO 350CC X UNIDAD[CAJA X 36', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 950.00, false, false, null),
  ('014B', 'BIDON AGUAS DEL SUR 6L', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1200.00, false, false, null),
  ('001VO400', 'VASO OSLO 400CC X UNIDAD[CAJA X 36', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('032BC', 'BUENOS AIRES CAB X 750', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2200.00, false, false, null),
  ('001VSEE', 'VASO SEELZE X UNIDAD [CAJA X48 U].', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1050.00, false, false, null),
  ('032BM', 'BUENOS AIRES MALB X 750 ML', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2200.00, false, false, null),
  ('020VBA', 'VODKA ABSOLUT APPLE 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 19000.00, false, false, null),
  ('042CB', 'CHAMPAGNE CANCILLER XXV BLEND DCE', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1800.00, false, false, null),
  ('020VSKR', 'VODKA SKYY RASPBERRY X 750', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9000.00, false, false, null),
  ('001CHE', 'CHOP ESCUDO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1490.00, false, false, null),
  ('020VSTF', 'VODKA SMIRNOFF TROPICAL FRUITS 700', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6800.00, false, false, null),
  ('001CHN', 'CHOPP NOCERA BIRRA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2600.00, true, true, '/images/nocera-nn.png'),
  ('044N', 'WISKY NOCERA 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 25000.00, true, true, '/images/nocera-nn.png'),
  ('002CZX', 'COCA ZERO 500CCX12U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 17000.00, false, false, null),
  ('304', 'YERBA MAÑANITAX500GRS [10U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1850.00, false, false, null),
  ('039CM', 'COLECCION PRIVADA MALBEC 750 ML [', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5850.00, false, false, null),
  ('305', 'YERBA TARAGUI X500GRS [10U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1860.00, false, false, null),
  ('001CNO', 'COPA NORUEGA CERVEZA X UNIDAD [CAJ', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1170.00, false, false, null),
  ('324', 'YERBA TRANKERA X 500GR X12', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 15000.00, false, false, null),
  ('001CG', 'COPON GOURMET[CAJAX36U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1610.00, false, false, null),
  ('019ZBD', 'ZUMUVA BCO DULCE TETRA 1LX12', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 16000.00, false, false, null),
  ('400DC', 'DETERGENTE COLAGENO 750C', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1030.00, false, false, null),
  ('400DA', 'DETERGENTE HEROE ALOE 750 C', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1030.00, false, false, null),
  ('400DL', 'DETERGENTE HEROE LIMON 750C', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1030.00, false, false, null),
  ('001DB', 'DISPENSER BIRRERO + BARRIL DE 3 L', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 23000.00, false, false, null),
  ('011A', 'AGUA CIMES 2.LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 3650.00, false, false, null),
  ('035EM', 'ELEGIDO MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3900.00, false, false, null),
  ('013AEC', 'AGUA SANO CORAZON 500CCX12U', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 2800.00, false, false, null),
  ('038EM', 'ELEMENTOS MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4300.00, false, false, null),
  ('013A', 'AGUA VILLA MANAOS 2LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 4000.00, false, false, null),
  ('001BC', 'ENERGIZANTE BALY CEREZA S/AZ X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9400.00, false, false, null),
  ('013AC', 'AGUA VILLA MANAOS 600 X 12', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 4500.00, false, false, null),
  ('001BDU', 'ENERGIZANTE BALY DURAZNO X6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('025AE', 'AGUA VILLAVICENCIO 1/5 X6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7000.00, false, false, null),
  ('001B2FT', 'ENERGIZANTE BALY FRUTAS TROPICALES', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 22000.00, false, false, null),
  ('025AEC', 'AGUA VILLAVICENCIO 500CCX12', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 8400.00, false, false, null),
  ('001BF', 'ENERGIZANTE BALY FRUTAS TROPICALES', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('001B2FD', 'ENERGIZANTE BALY FRUTILLA DURAZNO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 22000.00, false, false, null),
  ('014FL', 'BAGGIO FRESH LIMONE 1.5X6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7200.00, false, false, null),
  ('001B2MZ', 'ENERGIZANTE BALY MANZANA VERDE 2', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 22000.00, false, false, null),
  ('014FMI', 'BAGGIO FRESH MIX FRUTAL 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7200.00, false, false, null),
  ('001BPM', 'ENERGIZANTE BALY PROTEIN MUSCLE X', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 14400.00, false, false, null),
  ('014FN', 'BAGGIO FRESH NARANJA 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7200.00, false, false, null),
  ('001BS', 'ENERGIZANTE BALY SANDIA X6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('014FNB', 'BAGGIO FRESH NJA DCE 1.25LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 14520.00, false, false, null),
  ('001B2T', 'ENERGIZANTE BALY TRADICIONAL 2 L X', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 22000.00, false, false, null),
  ('014FPO', 'BAGGIO FRESH POMELO 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7200.00, false, false, null),
  ('001EG', 'ENSALADERA GRANDE X UNIDAD X8U.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1880.00, false, false, null),
  ('014MU8', 'BAGGIO PRONTO MULTIFRUTA 1LX8', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 14300.00, false, false, null),
  ('004CX', 'FANTA 500CCX12U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 17000.00, false, false, null),
  ('014MUC', 'BAGGIO PRONTO MULTIFRUTA 200CCX18', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 8700.00, false, false, null),
  ('017N', 'FERNET NERO53 750 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6500.00, false, false, null),
  ('014N8', 'BAGGIO PRONTO NARANJA 1LX8', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 12800.00, false, false, null),
  ('017NB', 'FERNET NERO53 BERRIES 750 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6500.00, false, false, null),
  ('012B', 'BIDÒN CIMES 6 LTS', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 1500.00, false, false, null),
  ('017NCI', 'FERNET NERO53 CITRUS 750 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6500.00, false, false, null),
  ('001RA', 'FERNET F3 1LX6U', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 5400.00, false, false, null),
  ('017NM', 'FERNET NERO53 MARACUYA 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6500.00, false, false, null),
  ('004EJ', 'JUGO BAGGIO NARANJA 100% 1LX12U.', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 34000.00, false, false, null),
  ('001NFP', 'FRAPERA NOCERA CLASICAS', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 18000.00, true, true, '/images/nocera-nn.png'),
  ('010AG', 'KNORR CALDO DE CARNE X2U[24U]', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 550.00, false, false, null),
  ('337PJF', 'GALLETITA JALEA FRAMBUEZA X 160 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 920.00, false, false, null),
  ('013LN', 'MANAOS LATA NARANJA 354CCX24U', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 17500.00, false, false, null),
  ('337PF', 'GALLETITA PITUSA FRUTILLA X 160 G', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 920.00, false, false, null),
  ('013PMZ', 'PLACER MANZANA 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 6100.00, false, false, null),
  ('337PMU', 'GALLETITA PITUSA MOUSE 160GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 920.00, false, false, null),
  ('013PMZU', 'PLACER MANZANA 1/5 X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 1100.00, false, false, null),
  ('337PV', 'GALLETITA PITUSA VAINILLA X 160 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 920.00, false, false, null),
  ('013PMZC', 'Placer Manzana 500ccx12', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 6300.00, false, false, null),
  ('020GB', 'GINEBRA BOLS 1L [UD][6]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8300.00, false, false, null),
  ('013PN', 'PLACER NARANJA 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 6100.00, false, false, null),
  ('038HC', 'HARINA CAÑUELAS 000 1 K', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 850.00, false, false, null),
  ('013PNC', 'PLACER NARANJA 500CCX12', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 6300.00, false, false, null),
  ('038M', 'HARINA MORIXE 0000 1 KG', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('012', 'SODA CIMES 2Lx6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7050.00, false, false, null),
  ('001BH', 'HEINEKEN LATON X24U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 75900.00, false, false, null),
  ('013', 'SODA MANAOS 2.25LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 7900.00, false, false, null),
  ('300JA', 'JABON ALA LIQUIDO VIVERE X 3LT', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 7830.00, false, false, null),
  ('014', 'SODA MASS 1.75', 'Producto importado desde lista de precios L1.19.9.', null, 'aguas-jugos-sodas', null, null, null, 5500.00, false, false, null),
  ('222L', 'LARGUITO DE QUESO CAPULLITO X80G', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 500.00, false, false, null),
  ('300LH', 'LAVANDINA HEROE 2 L', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1310.00, false, false, null),
  ('201T', 'Leche Descremada Brick 1L SERENIS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2500.00, false, false, null),
  ('020DC', 'LICOR DULCE DE LECHE CUSENIER X 7', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5600.00, false, false, null),
  ('309', 'ACEITE CAÑUELAS 1./5 GIRASOL X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6100.00, false, false, null),
  ('020CC', 'LICOR CAFE AL COGNAC CUSENIER X 70', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5000.00, false, false, null),
  ('303C', 'ACEITE CAÑUELAS GIRASOL 900CC -12-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3600.00, false, false, null),
  ('020CHC', 'LICOR CHOCOLATE CUSENIER X 700', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5600.00, false, false, null),
  ('035B4AU', 'ACEITE DE GIRASOL GRISOL X900CC [1', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2300.00, false, false, null),
  ('020HC', 'LICOR DE HUEVO CUSENIERX700', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5600.00, false, false, null),
  ('300A', 'ACEITE DOÑA TOTA 10L', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 24350.00, false, false, null),
  ('020MC', 'LICOR MENTA CUSENIER 6 X 700 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5100.00, false, false, null),
  ('301', 'ACEITE GIRASOL PREMIER 900CC-12-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2350.00, false, false, null),
  ('001MR', 'MATE RAICES X24U.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6330.00, false, false, null),
  ('308', 'ACEITE OLIVA OLIVARIA 500ml', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6600.00, false, false, null),
  ('001MTA', 'MATECOCIDO TARAGÜI X25[X10U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('212AD', 'ALFAJOR CAPITAN BLANCO SIMPLE [36', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('352SM', 'MIX DE SEMILLAS[GIRASOL.CHIA.SESAM', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4200.00, false, false, null),
  ('330T', 'ALFAJOR CAPITAN CH. NEGRO SIMPLE [', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('352S', 'MIX FRUTOS SECO.SIN MANIX500 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9000.00, false, false, null),
  ('039AN', 'ALFAJOR DE SIATO BLANCOX60GRS [12U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1000.00, false, false, null),
  ('032NC', 'NAC Y CRIADO MAL X 750 ML', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2160.00, false, false, null),
  ('121Q', 'ALFAJOR DE SIATO NEGRO X60GRS [12U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1000.00, false, false, null),
  ('001NBDS', 'NOCERA BELGIAN DARK STRONG ALE 750', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 10500.00, true, true, '/images/nocera-nn.png'),
  ('014AT', 'ALFAJOR GUAYMALLEN CH BLANCO SIMP', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 255.00, false, false, null),
  ('001NBB', 'NOCERA BIRRA BELGIAN RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3900.00, true, true, '/images/nocera-nn.png'),
  ('014AL', 'ALFAJOR GUAYMALLEN CH NEGRO SIMPL', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 255.00, false, false, null),
  ('001NH', 'NOCERA BIRRA HONEY 1L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2800.00, true, true, '/images/nocera-nn.png'),
  ('035AP', 'ALICANTE SOPA CAMPESTRE CON FIDEOS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1600.00, false, false, null),
  ('001NK', 'NOCERA BIRRA KÖLSCH 1 L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2800.00, true, true, '/images/nocera-nn.png'),
  ('038ARC', 'ALICANTE SOPA CREMA ZAPALLO 73GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1600.00, false, false, null),
  ('001N', 'NOCERA BIRRA NEIPA 1 L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3900.00, true, true, '/images/nocera-nn.png'),
  ('040AO', 'ALICANTE SOPA FIDEOS Y VERDURASX73', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1600.00, false, false, null),
  ('001NN', 'NOCERA BIRRA NN 1 L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2790.00, true, true, '/images/nocera-nn.png'),
  ('045', 'ALMOHADITAS DE AVENA RELLENAS [FRU', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5500.00, false, false, null),
  ('001NRI', 'NOCERA BIRRA RED IPA 1 L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3900.00, true, true, '/images/nocera-nn.png'),
  ('045AM', 'ALMOHADITAS DE AVENA RELLENAS [LIM', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5500.00, false, false, null),
  ('050T', 'NORTON COSECHA TARDIA TINTO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 520.00, false, false, null),
  ('045AR', 'ALMOHADITAS DE AVENA RELLENAS[CHOC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6200.00, false, false, null),
  ('220ACH', 'PAPAS CHIL 6 X 500', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6900.00, false, false, null),
  ('270K', 'ARROZ MONEDA LARGO FINO 1 KILO[5]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1050.00, false, false, null),
  ('219OK', 'PAPAS LISTAS KETCHUP 65 GRSX 23 U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1300.00, false, false, null),
  ('500AJ', 'ARROZ OKARA X1KG [10]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 850.00, false, false, null),
  ('219CQC', 'PAPAS LISTAS CLASICAS QUESO CREMA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1250.00, false, false, null),
  ('452', 'BOLSAS CONSORCIO 60 X90 -50-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 6500.00, false, false, null),
  ('404PF', 'PAPEL HIGENICO FLORIPEL 4 X 30M', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1480.00, false, false, null),
  ('453', 'BOLSAS CONSORCIO 70 X1MT-50-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8100.00, false, false, null),
  ('035BCH', 'PATRIDGE MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4750.00, false, false, null),
  ('454', 'BOLSAS CONSORCIO 80 X1.10 -50-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 10600.00, false, false, null),
  ('019F', 'POWER FRUT TROPICALES 995 X6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9800.00, false, false, null),
  ('450', 'BOLSAS RESIDUOS 45 X60 -50-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2400.00, false, false, null),
  ('019M', 'POWER MOUNT BLAST 995 X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9800.00, false, false, null),
  ('451', 'BOLSAS RESIDUOS 50 X70 -50-', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3100.00, false, false, null),
  ('500F', 'QUERUBIN SUAVIZANTE FLORES CITRICA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2340.00, false, false, null),
  ('330NC', 'BOMBON ESPECIAL TERCER FRIO [24U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1650.00, false, false, null),
  ('500FB', 'QUERUBIN SUAVIZANTE FLORES DEL BOS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2340.00, false, false, null),
  ('026PC', 'CAFE EN SAQUITOS LA MORENITA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4750.00, false, false, null),
  ('500FC', 'QUERUBIN SUAVIZANTE FLORES X 900', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2340.00, false, false, null),
  ('01', 'CAFE LA VIRGINIA EN SAQUITOS [20U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4900.00, false, false, null),
  ('121B', 'QUESO CREMOSO LOS TRONCOS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1320.00, false, false, null),
  ('014MC', 'CIRUELA PASAS 500GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5800.00, false, false, null),
  ('352ROCK', 'ROCKLETS [500GRS]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12600.00, false, false, null),
  ('001CCH', 'COPA DE CHAMPAGNE NOCERA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('020RHE', 'RON HAVANA CLUB ESPECIAL 750 CC[U', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12200.00, false, false, null),
  ('001R', 'COPA DE VIDRIO DUBLIN. NOCERA BIRR', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 6000.00, true, true, '/images/nocera-nn.png'),
  ('046DES', 'SAL FINA DOS ESTRELLAS X 500 GR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 700.00, false, false, null),
  ('001BM', 'DON SATUR BIZCOCHITOS AGRIDULCES X', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('001SL7', 'SCHENNEIDER LATON X 24 UD 710', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 47800.00, false, false, null),
  ('001BCH', 'DON SATUR BIZCOCHITOS SALADOS 200G', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1100.00, false, false, null),
  ('337S', 'SCHWEP TÓNICA 1.5LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 17250.00, false, false, null),
  ('106S', 'FETAS TONADITA CHEDDAR [8U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2300.00, false, false, null),
  ('280MB', 'HALCON GRASA BOBINA 500GRS [10U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2500.00, false, false, null),
  ('001V', 'VASO PINTA VIDRIO NOCERA BIRRA XUD', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 6000.00, true, true, '/images/nocera-nn.png'),
  ('308C', 'HARINA CASERITA 000 X1KG[10]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 800.00, false, false, null),
  ('001W', 'WARSTEINER 1L X 12 RETORNABLE', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 19000.00, false, false, null),
  ('038TAM', 'HARINA DE ALMENDRAS 1KG.', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5800.00, false, false, null),
  ('038TAC', 'HARINA DE ALMENDRAS 500GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 3000.00, false, false, null),
  ('300', 'JABÒN LÌQUIDO ROPA MATIC LIMPIA GO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4700.00, false, false, null),
  ('293N2', 'KETCHUP HELLMANS X250GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1700.00, false, false, null),
  ('101C', 'FIAMBRE DE PALETA GRASSETO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 4800.00, false, false, null),
  ('014ACC', 'KNORR CALDO DE GALLINAX2U [24]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 550.00, false, false, null),
  ('101CH', 'JAMÓN COCIDO CHICO CHAMPION[3802]', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 3980.00, false, false, null),
  ('014AEG', 'KNORR CALDO DE VERDURA X2U [24]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 550.00, false, false, null),
  ('101', 'LUVIANKA FIAMB.COC.PATA DE CERDO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 7600.00, false, false, null),
  ('201', 'Leche Descremada Sachets 1L SEREN', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1900.00, false, false, null),
  ('122G', 'MUZZARELLA EL GAUCHITO cilindri 2k', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 8421.84, false, false, null),
  ('200T', 'Leche entera Brick x1L SERENISIMA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2500.00, false, false, null),
  ('100CH', 'PALETA DE CERDO COCIDACHICA CHAMPI', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 3700.00, false, false, null),
  ('200', 'Leche entera sachets 1L SERENESIMA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1900.00, false, false, null),
  ('119G', 'PROVOLETA EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 17000.00, false, false, null),
  ('001MH', 'MAPLE DE HUEVO BLANCO N"2', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4300.00, false, false, null),
  ('128PG', 'PROVOLONE EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 19200.00, false, false, null),
  ('001MH1', 'MAPLE HUEVO BLANCO N"1', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 4900.00, false, false, null),
  ('121F', 'QUESO CREMOSO DON FIRTICCHIO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 8300.00, false, false, null),
  ('293NC', 'MAYONESA NATURA 250', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1550.00, false, false, null),
  ('121G', 'QUESO CREMOSO EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 6438.27, false, false, null),
  ('001MO', 'MOLTO PURE 520GRS.[ X24U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 800.00, false, false, null),
  ('127G', 'QUESO MAQUINA EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 10860.00, false, false, null),
  ('106L', 'MORTADELA CALCHAQUI BOCHA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9850.00, false, false, null),
  ('120G', 'QUESO PATEGRAS EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 15810.00, false, false, null),
  ('322', 'NUEVO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 89.00, false, false, null),
  ('121GP', 'QUESO POR SALUT SIN SAL EL GAUCHIT', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 9350.00, false, false, null),
  ('014C', 'PALITO BOMBON CROCANTE TERCER FRIO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 700.00, false, false, null),
  ('121GPS', 'QUESO PORT SALUT CON SAL EL GAUCH', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 9350.00, false, false, null),
  ('330N', 'PALITO BOMBON TERCER FRIO [40U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 600.00, false, false, null),
  ('123G', 'QUESO REGGIANITO EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 18100.00, false, false, null),
  ('300CC', 'PALITO DE AGUA CON CREMA TERCER FR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 200.00, false, false, null),
  ('129G', 'QUESO SARDO SEMI EST.EL GAUCHITO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 15400.00, false, false, null),
  ('300CCC', 'PALITO DE AGUA TERCER FRIO [40U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 160.00, false, false, null),
  ('103CH', 'SALAME MILÀN CHICO CHAMPION', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 10450.00, false, false, null),
  ('300C', 'PALITO DE CREMA TERCER FRIO [40U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 300.00, false, false, null),
  ('104', 'SALAMINES 214 PICADO FINO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 13400.00, false, false, null),
  ('212', 'PALITO SOMBRERO LOCO TERCER FRIO [', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1000.00, false, false, null),
  ('103', 'SALAMINES EL NAHUEL P/FINO', 'Producto importado desde lista de precios L1.19.9.', null, 'fiambreria', null, null, null, 15400.00, false, false, null),
  ('404RC', 'ROLLO DE COCINA CANIPEL X8', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 10500.00, false, false, null),
  ('104LC', 'SALAMINES EL NAHUEL P/GRUESO', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 15400.00, false, false, null),
  ('021SPO', 'SAVORA X250GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1650.00, false, false, null),
  ('202V', 'SWIFT PATE X90GRS [24U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 950.00, false, false, null),
  ('007A', '7uP 2L X8', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 23000.00, false, false, null),
  ('500PZ', 'TERCER FRIO ALMENDRADO FIESTA [30', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 31500.00, false, false, null),
  ('001LP', 'COCA 1L.PETX8U.', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 20050.00, false, false, null),
  ('042TO', 'TERCER FRIO BARRA ALMENDRADO [18]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 9000.00, false, false, null),
  ('002E', 'COCA COLA 1.5 X 8', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 27100.00, false, false, null),
  ('301OE', 'TERCER FRIO BARRA TRICOLOR', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 8000.00, false, false, null),
  ('002A9', 'COCA COLA RETORNABLE 2000CCX9U.', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 26500.00, false, false, null),
  ('014AB', 'TERCER FRIO BOMBON ESCOCES [6U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('002AZ9', 'COCA COLA ZERO 2000CCX9U', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 26450.00, false, false, null),
  ('500PN', 'TERCER FRIO BOMBON ROCHER[6U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('002BR', 'COCA-COLA 1L VIDRIO RETORNABLE', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 2300.00, false, false, null),
  ('032DU', 'TERCER FRIO BOMBON SUIZO [6U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('002A6', 'COCA-COLA 2.25L X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 25500.00, false, false, null),
  ('500P', 'TERCER FRIO BOMBON TENTACION [6U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 12000.00, false, false, null),
  ('002AZ6', 'COCA-COLA SIN AZCÚAR 2.25L X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 25500.00, false, false, null),
  ('500PNG', 'TERCER FRIO TORTA HELADA[20U.]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 21700.00, false, false, null),
  ('004E', 'FANTA 1.5Lx8', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 27100.00, false, false, null),
  ('026PD', 'TERCER FRIO TRICOLOR FIESTA[30U]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 27500.00, false, false, null),
  ('004A6', 'FANTA 2.25LX6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 25500.00, false, false, null),
  ('407', 'TOMATE TRITURADO CAPILLA MENDOCINA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1300.00, false, false, null),
  ('013CLS', 'MANAOS CITRUS 2.25LX6U SIN AZUCAR', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 6000.00, false, false, null),
  ('001VNG', 'VASO GIN IMPRONTA HUELLA', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 5000.00, false, false, null),
  ('013CC', 'MANAOS COLA 1.500 CCX6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 6000.00, false, false, null),
  ('001VNIP', 'VASO NOCERA IPA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 6000.00, true, true, '/images/nocera-nn.png'),
  ('013C', 'MANAOS COLA 2.25L X6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 8500.00, false, false, null),
  ('302', 'YERBA AMANDA X500GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1900.00, false, false, null),
  ('013CCC', 'MANAOS COLA X 600CCX12', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 7600.00, false, false, null),
  ('321', 'YERBA PLAYADITO 500GR [X', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 2210.00, false, false, null),
  ('013LLCC', 'MANAOS LIMA-LIMÓN 600CCX12', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 7600.00, false, false, null),
  ('323', 'YERBA UNIÒN 500GR UD [10]', 'Producto importado desde lista de precios L1.19.9.', null, 'almacen', null, null, null, 1800.00, false, false, null),
  ('013PBL', 'MANAOS POM BLANCO SIN AZUCAR 2.25L', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 6000.00, false, false, null),
  ('013PRC', 'PLACER POMELO ROSADO 500CC', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 6300.00, false, false, null),
  ('001S', 'SPEED ENERGIZANTE 250CC UD', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 1250.00, false, false, null),
  ('003E', 'SPRITE 1.5X8', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 27100.00, false, false, null),
  ('001AIR', 'ANDES IPA RETORNABLE 1L. X12U.', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 0.00, false, false, null),
  ('003A6', 'SPRITE 2.25 LX 6', 'Producto importado desde lista de precios L1.19.9.', null, 'gaseosas', null, null, null, 25500.00, false, false, null),
  ('001ARR', 'ANDES RUBIA RETORNABLE 1LX12U.', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 27000.00, false, false, null),
  ('001NB', 'BOTELLA PLÁSTICO NOCERA 1 L', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 300.00, true, true, '/images/nocera-nn.png'),
  ('001BL', 'BRAHMA LATA 473CCX24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 41300.00, false, false, null),
  ('001BLT', 'BRAHMA LATÒN 710CC.X16U.', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 36400.00, false, false, null),
  ('015M', 'Americano Manon 950cc.', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 1800.00, false, false, null),
  ('001B', 'BRHAMA 1LX12U', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 36800.00, false, false, null),
  ('301G', 'BROK SHOT 45°', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 1300.00, false, false, null),
  ('001BUL4', 'BUDWEISER LATA 410CCX24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 39000.00, false, false, null),
  ('016', 'CAMPARI 750CC X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 10600.00, false, false, null),
  ('001NFPL', 'FRAPERA NOCERA CON PORRON DE LUPUL', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 20000.00, true, true, '/images/nocera-nn.png'),
  ('022P', 'CAÑA PALANCA 950CC UD', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3000.00, false, false, null),
  ('100GWP', 'GROWLER NOCERA PLASTICO 2 L', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 400.00, true, true, '/images/nocera-nn.png'),
  ('DV1', 'DR LEMON VODKA 1L [UD] -X12-', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2950.00, false, false, null),
  ('001GW', 'GROWLER 2L. VIDRIO. NOCERA BIRRA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 7000.00, true, true, '/images/nocera-nn.png'),
  ('017', 'FERNET BRANCA 750 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 17500.00, false, false, null),
  ('001H', 'Heineken 1Lx12', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 55500.00, false, false, null),
  ('017M', 'FERNET BRANCA MENTA 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 7300.00, false, false, null),
  ('001HL', 'HEINEKEN LATA 473CC X 24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 63800.00, false, false, null),
  ('016RF', 'FERNET COLA MASS FORTE', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 5000.00, false, false, null),
  ('001IG', 'IGUANA 1 L X 12', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 27000.00, false, false, null),
  ('015', 'GANCIA 950CC XUD -12-', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 7100.00, false, false, null),
  ('001SL4', 'Isenbeck Lata 473ccx24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 28000.00, false, false, null),
  ('020GI', 'GIN 40° NEW STYLE 1L -6-', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3800.00, false, false, null),
  ('500A', 'LATA AMERICAN APA NOCERA BIRRA 473', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 1170.00, true, true, '/images/nocera-nn.png'),
  ('020GIBO', 'GIN BOMBAY SAPPHIRE 750ML', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 32000.00, false, false, null),
  ('001QLT', 'LATON QUILMES 710CCX16U', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 29500.00, false, false, null),
  ('020GIG', 'GIN GORDON´S 700CC -12-', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 9300.00, false, false, null),
  ('001MP', 'MALTA ÁVILA PORRÓN 500CC [UD]', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 1680.00, false, false, null),
  ('001GNL', 'GIN IMPRONTA LONDON DRY X750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 15000.00, false, false, null),
  ('001M', 'MILLER 1L X12', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 38500.00, false, false, null),
  ('001GNLR', 'GIN IMPRONTA LONDON EN BARRICA DE', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 20000.00, false, false, null),
  ('001NBWN', 'NOCERA BARLEY WINE 750CC [NO RETOR', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 10500.00, true, true, '/images/nocera-nn.png'),
  ('001GNP', 'GIN IMPRONTA PINK X 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 15000.00, false, false, null),
  ('500N', 'NOCERA BIRRA NEIPA LATA 473 CC', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 1520.00, true, true, '/images/nocera-nn.png'),
  ('020GR', 'GRANADINA 1L', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3300.00, false, false, null),
  ('001NIP', 'NOCERA BIRRA AMERICAN IPA 1L RECAR', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3900.00, true, true, '/images/nocera-nn.png'),
  ('001GNB', 'IMPRONTA GIFT BOX', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 30000.00, false, false, null),
  ('001NIPN', 'NOCERA BIRRA AMERICAN IPA 1L. [NO', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 4200.00, true, true, '/images/nocera-nn.png'),
  ('018J', 'JAGERMEISTER X 700ML', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 26900.00, false, false, null),
  ('001APN', 'NOCERA BIRRA APA CITRA 1L [ NO RET', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 4200.00, true, true, '/images/nocera-nn.png'),
  ('020C', 'LICOR DE CAFE COGNAC BAR&PUBS 17°.', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2780.00, false, false, null),
  ('001NS', 'NOCERA BIRRA DRY STOUT 1L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3900.00, true, true, '/images/nocera-nn.png'),
  ('020CH', 'LICOR DE CHOCOLATE X 1 L', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2780.00, false, false, null),
  ('001NSN', 'NOCERA BIRRA DRY STOUT 1L. [NO RET', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 4200.00, true, true, '/images/nocera-nn.png'),
  ('020F', 'LICOR DE FRUTILLA X 1 L', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2780.00, false, false, null),
  ('001GN', 'NOCERA BIRRA GOLDEN 1L [NO RETORNA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('020ME', 'LICOR DE MELÓN 20° 1L BAR&PUBS', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2780.00, false, false, null),
  ('001NG', 'NOCERA BIRRA GOLDEN 1L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2800.00, true, true, '/images/nocera-nn.png'),
  ('020MN', 'LICOR DE MENTA', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2800.00, false, false, null),
  ('001NHN', 'NOCERA BIRRA HONEY 1L [NO RETORNAB', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('020D', 'LICOR DULCE DE LECHE 20° 1L BAR&PU', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2780.00, false, false, null),
  ('001NISN', 'NOCERA BIRRA IMPERIAL STOUT [BARRI', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 10500.00, true, true, '/images/nocera-nn.png'),
  ('015M81', 'M81 VERMOUTH ROSSO', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 7500.00, false, false, null),
  ('001NI', 'NOCERA BIRRA IRISH RED 1L RECARGA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2800.00, true, true, '/images/nocera-nn.png'),
  ('020M', 'MARIPOSA LICOR MIEL X750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2800.00, false, false, null),
  ('001NIN', 'NOCERA BIRRA IRISH RED 1L. [ NO RE', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('001NBE', 'NOCERA BITER EDICION ESPECIAL', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 8000.00, true, true, '/images/nocera-nn.png'),
  ('001NNN', 'NOCERA BIRRA NN 1L [NO RETORNABLE]', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('001TSN', 'NOCERA TRIPLE SEC EDICIÓN ESPECIAL', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 9000.00, true, true, '/images/nocera-nn.png'),
  ('001RIN', 'NOCERA BIRRA RED IPA DE 1L[ NO RET', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 4200.00, true, true, '/images/nocera-nn.png'),
  ('001VN', 'NOCERA VERMUT EDICIÓN ESPECIAL', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 8000.00, true, true, '/images/nocera-nn.png'),
  ('001NBS', 'NOCERA BIRRA SAISON BARRICA 750CC[', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 11000.00, true, true, '/images/nocera-nn.png'),
  ('026CHO', 'PETACAS CHOCOLATE. NEW STYLE', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 1100.00, false, false, null),
  ('001NEE', 'NOCERA EDICION ESPECIAL 500ML', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 4000.00, true, true, '/images/nocera-nn.png'),
  ('026WG', 'PETACAS GLOUCENTER WISKY', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 1300.00, false, false, null),
  ('001GP', 'NOCERA GOLDEN PORRÓN 500CC', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2500.00, true, true, '/images/nocera-nn.png'),
  ('026CR', 'PETACAS WISKY CRIADORES UD', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2000.00, false, false, null),
  ('001NNP', 'NOCERA PORRÓN NN X 500CC', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2500.00, true, true, '/images/nocera-nn.png'),
  ('029CH', 'PETAKÓN CHOCOLATE 400CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 500.00, false, false, null),
  ('001NSIP', 'NOCERA SESSION IPA [RECARGA]', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3890.00, true, true, '/images/nocera-nn.png'),
  ('020R', 'RON NEW STYLE 1L 40°', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3900.00, false, false, null),
  ('001NSIPN', 'NOCERA SESSION IPA SIN ALCOHOL 1L', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 3500.00, true, true, '/images/nocera-nn.png'),
  ('021SH', 'SHERIDAN´S', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 36000.00, false, false, null),
  ('001NPI', 'PILUSO NOCERA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 17000.00, true, true, '/images/nocera-nn.png'),
  ('001GTL', 'SHOOTER GIN&TONIC LIMON X24U', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 19000.00, false, false, null),
  ('001NAP', 'PORRON APA NOCERA', 'Producto importado desde lista de precios L1.19.9.', null, 'productos-nocera', null, null, null, 2800.00, true, true, '/images/nocera-nn.png'),
  ('020LG', 'SMIRNOFF LATA GREEN APLPLE 24 X 47', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 56200.00, false, false, null),
  ('001BPMIX', 'PROMO BRAHMA MIXEADA [10U BRAHMA +', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 35300.00, false, false, null),
  ('020LR', 'SMIRNOFF LATA RED BERRIE 24 X 473', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 56200.00, false, false, null),
  ('001Q', 'QUILMES 1L X12', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 32000.00, false, false, null),
  ('020TC', 'TEQUILA CUERNAVACA 39º 1L X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 5550.00, false, false, null),
  ('001QL', 'QUILMES LATA 473CC X 24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 36000.00, false, false, null),
  ('020TM', 'TIA MARIA CLÁSICO 690CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 8000.00, false, false, null),
  ('001QB', 'QUILMES STOUT NEGRA 1LX12', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 32500.00, false, false, null),
  ('020VNS', 'VODKA 20 ° NEW STYLE SANDIA 1L', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2700.00, false, false, null),
  ('001SNL', 'SCHNEIDER LATA 473CCX24', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 39200.00, false, false, null),
  ('020VNME', 'VODKA 20° NEW STYLE MELÓN 1L', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2700.00, false, false, null),
  ('020VSKCO', 'VODKA SKY COSMIC 750CCX12U', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 9000.00, false, false, null),
  ('041R1', 'SIDRA 1888 UD', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 4950.00, false, false, null),
  ('044JD', 'WHISKY JACK DANIEL`S X 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 44000.00, false, false, null),
  ('041S1930', 'SIDRA 1930 DEMI SEC UNIDAD750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 1500.00, false, false, null),
  ('044J', 'WHISKY JAMESON 700CC', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 34000.00, false, false, null),
  ('041DVL', 'SIDRA DEL VALLE LATA 473CC. X24U', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 20300.00, false, false, null),
  ('044W', 'WHITE HORSE WISKY 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'cervezas', null, null, null, 15700.00, false, false, null),
  ('040V', 'SIDRA REINO DE CASTILLA 710CC[VIDR', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 8880.00, false, false, null),
  ('041V', 'SIDRA VICTORIA 720CC X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 10600.00, false, false, null),
  ('045AC', 'SOL PAMPEANO MOSTACHOL LISO X500GR', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 800.00, false, false, null),
  ('039AM', 'SOL PAMPEANO SPAGHETTI X500GRS[20U', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 850.00, false, false, null),
  ('351', 'ALMENDRAS PELADAS[NON PAREIL] 500G', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 17200.00, false, false, null),
  ('039ATD', 'SOL PAMPEANO TIRABUZON X500GRS[15]', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 850.00, false, false, null),
  ('352B', 'BANANA CHIPS X 500', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 8400.00, false, false, null),
  ('018B', 'TERMIDOR BLANCO 1Lx12', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 16550.00, false, false, null),
  ('220BO', 'BOLITA COLOR CAPULLITOS EN FLOR X', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 500.00, false, false, null),
  ('022TB', 'TORO CLÁSICO TINTO 1.125L X6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 15000.00, false, false, null),
  ('222C', 'CHIZITOS 80GR CAPULLITO EN FLOR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 500.00, false, false, null),
  ('022T', 'TORO CLÁSICO TINTO 750 CC X6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 12000.00, false, false, null),
  ('222B', 'CHIZITOS FRITBON 100GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 650.00, false, false, null),
  ('039TC', 'TRUMPETER CABERNET 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 7600.00, false, false, null),
  ('222A', 'CHIZITOS FRITBONX400GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 2200.00, false, false, null),
  ('039T', 'TRUMPETER MALBEC 750CC [UD]', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 7600.00, false, false, null),
  ('223CJ', 'MANI CROCANTE FRITBON SABORIZADO 1', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1400.00, false, false, null),
  ('019BD', 'UVITA BLANCO DULCE 1LX12', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 18000.00, false, false, null),
  ('223CC', 'MANI FRITBON CROCANTE CLASICO 160G', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1400.00, false, false, null),
  ('019TD', 'UVITA TINTO DULCE 1LX12', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 18000.00, false, false, null),
  ('223B', 'MANI FRITBON X 150GR-X24-', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1400.00, false, false, null),
  ('019TS', 'UVITA TINTO SECO 1Lx12', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 18000.00, false, false, null),
  ('225A', 'MANI MANITOON CON PIEL X900', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 5880.00, false, false, null),
  ('035C', 'UXMAL CABERNET SAUVIGNON 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3500.00, false, false, null),
  ('223BP', 'MANÌ PELADO FRITBON X 150GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1400.00, false, false, null),
  ('035M', 'UXMAL MALBEC 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3500.00, false, false, null),
  ('225BP', 'MANÍ PELADO SAB/EXTREM MANITOON 1', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 280.00, false, false, null),
  ('022B', 'VALDERROBLES MAGNUM 1.125 X 6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 21470.00, false, false, null),
  ('225AP', 'MANI PELADO X 900GS MANITON', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 5900.00, false, false, null),
  ('022V', 'VALDERROBLES VAR EUROPE 750X6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 3350.00, false, false, null),
  ('225', 'MANITÒN 70GR -48-', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 600.00, false, false, null),
  ('035VR', 'VENDIMIARIO LA RIOJA BLEND 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 2800.00, false, false, null),
  ('352C', 'MIX CERVECERO 500GR [ALMENDRA.CAJ', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 7500.00, false, false, null),
  ('024V', 'VIÑAS DE ALVEAR 1.250 x6', 'Producto importado desde lista de precios L1.19.9.', null, 'licores-aperitivos-whisky', null, null, null, 15000.00, false, false, null),
  ('352E', 'MIX FRUTAS SECAS .CON PASAS 500GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 7000.00, false, false, null),
  ('352', 'MIX FRUTAS SECAS ESPECIAL 500GR [N', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 11000.00, false, false, null),
  ('352T', 'MIX FRUTAS SECAS TROPICAL 500GR [', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 7200.00, false, false, null),
  ('350', 'NUECES PELADAS[CHANDLER X LIGHT] 5', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 11000.00, false, false, null),
  ('221J', 'PALITOS FRITBON JAMON X 120GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1000.00, false, false, null),
  ('221B', 'PALITOS FRITBON 120GR -30-', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 850.00, false, false, null),
  ('221A', 'PALITOS FRITBON 800GR [X6]', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 4400.00, false, false, null),
  ('221Q', 'PALITOS FRITBON C/QUESO 120GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1000.00, false, false, null),
  ('219PQ', 'PALITOS SALADOS LISTAS SABOR QUESO', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1000.00, false, false, null),
  ('220A', 'PAPAS FRITBON 500GR [X6]', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 5400.00, false, false, null),
  ('220C', 'PAPAS FRITBON 70GR-ROJAS', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 900.00, false, false, null),
  ('220CA', 'PAPAS FRITBON.70GR.viole', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 900.00, false, false, null),
  ('219CCH', 'PAPAS LISTAS CHEDDAR 65GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1300.00, false, false, null),
  ('219C', 'PAPAS LISTAS CLÁSICAS 60GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1000.00, false, false, null),
  ('219CJ', 'PAPAS LISTAS JAMÓN SERRANO 65GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1300.00, false, false, null),
  ('219CO', 'PAPAS LISTAS ONDULADAS 60GR', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1000.00, false, false, null),
  ('220P', 'PAPAS PAY FRITBON X 25 U 80 GRS', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 900.00, false, false, null),
  ('352P', 'PISTACHOS[CON CÁSCARA TOSTADO Y SA', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 21500.00, false, false, null),
  ('221C', 'PIZZITOS FRITBON 70GRS X24U', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 550.00, false, false, null),
  ('221P', 'Pizzitos X 80 GR CAPULLITOS EN FLO', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 500.00, false, false, null),
  ('001TO', 'TORRONCINO ROJO', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1390.00, false, false, null),
  ('001TOV', 'TORRONCINO VERDE', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 1390.00, false, false, null),
  ('224', 'TUTUCA CAPULLITO EN FLOR -24', 'Producto importado desde lista de precios L1.19.9.', null, 'snacks', null, null, null, 500.00, false, false, null),
  ('014EAN', '21 BLACK MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 2600.00, false, false, null),
  ('038AM', 'ALMA MORA MALBEC 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4700.00, false, false, null),
  ('035AC', 'ALTO UXMAL CABERNET MERLOT', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 5800.00, false, false, null),
  ('041AFL', 'ANANA FIZZ DEL VALLE LATA473CC. X2', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 20300.00, false, false, null),
  ('065A', 'ANELIS CABERNET FRANC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 5040.00, false, false, null),
  ('035BC', 'BRAVIO CABERNET SAU 750CC XUD', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3000.00, false, false, null),
  ('035BM', 'BRAVIO MALBEC 750CC XUD', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3000.00, false, false, null),
  ('023CM', 'CAPILLA MENDOCINA 1.125CC.X6U.', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 12000.00, false, false, null),
  ('042FDPB', 'COMBO BRANCA DE 750CC + 2U. COCA D', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 20999.00, false, false, null),
  ('010A', 'COMBO NERO + 2U COCA DE LITRO', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 13000.00, false, false, null),
  ('050', 'COSECHA TARDÍA NORTÓN BL.DULCE X U', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4200.00, false, false, null),
  ('023DB', 'DOMADOS BISTRO ASSEMBLAGE ROUGE 20', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 7910.00, false, false, null),
  ('023DEC', 'DOMADOS ESTATE CAB.FRANC & MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 7190.00, false, false, null),
  ('023DER', 'DOMADOS ESTATE RED BLEND 2019 [UD]', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 7190.00, false, false, null),
  ('023DRC', 'DOMADOS RESERVA CAB. SAUVIGNON X U', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 11450.00, false, false, null),
  ('023DRP', 'DOMADOS RESERVA PINOT NOIR XU', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 5280.00, false, false, null),
  ('037', 'DON VALENTÌN LACRADO X UD', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 2800.00, false, false, null),
  ('001BTCH', 'E-PACK GENTILEZA TINTO 1.125CCX6U.', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 9000.00, false, false, null),
  ('001BTM', 'E-PACK GENTILEZA TINTO PATERO 1.12', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 10000.00, false, false, null),
  ('034EC', 'ESMERALDA CABERNET SAUVG 750CC U', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4000.00, false, false, null),
  ('023EF', 'ESMERALDA FERNANDEZ RED BLEND 750C', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3820.00, false, false, null),
  ('036S', 'ESTIBA I SYRAH 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3100.00, false, false, null),
  ('042FD', 'FEDERICO DE ALVEAR EXTR DULCE CHAM', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4300.00, false, false, null),
  ('042FDS', 'FEDERICO DE ALVEAR SWEET', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3500.00, false, false, null),
  ('038FM', 'FINCA LAS MORAS MALBEC 750CC [X6]', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3500.00, false, false, null),
  ('041FFL', 'FRESA FIZZ DEL VALLE LATA 473CC.X2', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 20300.00, false, false, null),
  ('039IM', 'HORMIGA NEGRA 750CC.', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 2300.00, false, false, null),
  ('023BMR', 'LA LUCILA MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 11500.00, false, false, null),
  ('065N', 'LA NUAGE MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 2450.00, false, false, null),
  ('023P', 'LA PRUDENCIA 1.125L R/BLEND MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 1030.00, false, false, null),
  ('047LPM', 'LAS PERDICES MALBEC 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 7250.00, false, false, null),
  ('039N', 'LOS ARBOLES MALBEC 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4000.00, false, false, null),
  ('039LCM', 'LUIGI BOSCA CABERNET SAUV. DE SANG', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 12000.00, false, false, null),
  ('022R', 'MICHEL ABEL TINTO 700cc.X6. TAPA R', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 8200.00, false, false, null),
  ('042NE', 'NORTON SELECT MALBEC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4900.00, false, false, null),
  ('039AC', 'PRESTO PRONTA HARINA DE MAIZ X500G', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 1400.00, false, false, null),
  ('039RM', 'RUTINI MALBEC 750CC[UD]', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 23000.00, false, false, null),
  ('023SF12', 'SAN FELIPE 12 UVAS 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 4150.00, false, false, null),
  ('023SFT', 'SAN FELIPE TINTO C 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 3950.00, false, false, null),
  ('023FMI', 'SANTA FILOMENA MISTELA 700', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 1100.00, false, false, null),
  ('023F', 'SANTA FILOMENA PATERO TTO X 1125CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 16200.00, false, false, null),
  ('037FM', 'SANTA FLORENTINA MALBEC/SYRAH 750C', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 2310.00, false, false, null),
  ('037FT', 'SANTA FLORENTINA TORR/CHARD 750CC', 'Producto importado desde lista de precios L1.19.9.', null, 'vinos-champagnes', null, null, null, 1570.00, false, false, null)
)
insert into public.products (
  code,
  name,
  description,
  brand,
  category_id,
  presentation,
  unit,
  pack_quantity,
  price,
  active,
  featured,
  nocera_product,
  image_path,
  stock_status
)
select
  source.code,
  source.name,
  source.description,
  source.brand,
  categories.id,
  source.presentation,
  source.unit,
  source.pack_quantity::numeric,
  source.price::numeric,
  true,
  source.featured,
  source.nocera_product,
  source.image_path,
  'available'
from source
left join public.categories on categories.slug = source.category_slug
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  brand = excluded.brand,
  category_id = excluded.category_id,
  presentation = excluded.presentation,
  unit = excluded.unit,
  pack_quantity = excluded.pack_quantity,
  price = excluded.price,
  active = excluded.active,
  featured = excluded.featured,
  nocera_product = excluded.nocera_product,
  image_path = excluded.image_path,
  stock_status = excluded.stock_status;
