import type { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "productos-nocera",
    name: "Productos Nocera",
    description: "Cervezas, vasos, growlers y ediciones propias encontradas en la lista.",
    active: true,
    sortOrder: 0
  },
  {
    id: "aguas-jugos-sodas",
    name: "Aguas, jugos y sodas",
    description: "Aguas, sodas, jugos y bebidas sin alcohol.",
    active: true,
    sortOrder: 1
  },
  {
    id: "almacen",
    name: "Almacen",
    description: "Productos de almacen y consumo general.",
    active: true,
    sortOrder: 2
  },
  {
    id: "gaseosas",
    name: "Gaseosas",
    description: "Gaseosas retornables, PET y latas.",
    active: true,
    sortOrder: 3
  },
  {
    id: "cervezas",
    name: "Cervezas",
    description: "Cervezas industriales, artesanales y presentaciones retornables.",
    active: true,
    sortOrder: 4
  },
  {
    id: "licores-aperitivos-whisky",
    name: "Licores, aperitivos y whisky",
    description: "Bebidas espirituosas, aperitivos, vermut, gin y whisky.",
    active: true,
    sortOrder: 5
  },
  {
    id: "snacks",
    name: "Snacks",
    description: "Papas, snacks, galletitas y productos para consumo rapido.",
    active: true,
    sortOrder: 6
  },
  {
    id: "vinos-champagnes",
    name: "Vinos y champagnes",
    description: "Vinos, espumantes y etiquetas para gastronomia.",
    active: true,
    sortOrder: 7
  },
  {
    id: "fiambreria",
    name: "Fiambreria",
    description: "Fiambres y quesos de la lista mayorista.",
    active: true,
    sortOrder: 8
  }
];

export const products: Product[] = [
  {
    id: "001nn",
    code: "001NN",
    name: "Nocera Birra NN",
    description: "Producto propio Nocera cargado desde la lista de precios.",
    brand: "Nocera Birra",
    categoryId: "productos-nocera",
    presentation: "1 L recarga",
    unit: "recarga",
    packQuantity: 1,
    price: 2790,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: true,
    noceraProduct: true,
    image: "/images/nocera-nn.png",
    updatedAt: "2026-09-19"
  },
  {
    id: "500n",
    code: "500N",
    name: "Nocera Birra NEIPA lata",
    description: "Cerveza Nocera en lata individual segun lista vigente.",
    brand: "Nocera Birra",
    categoryId: "productos-nocera",
    presentation: "473 cc",
    unit: "lata",
    packQuantity: 1,
    price: 1520,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: true,
    noceraProduct: true,
    image: "/images/nocera-nn.png",
    updatedAt: "2026-09-19"
  },
  {
    id: "001ni",
    code: "001NI",
    name: "Nocera Birra Irish Red",
    description: "Recarga de cerveza Nocera para venta por litro.",
    brand: "Nocera Birra",
    categoryId: "productos-nocera",
    presentation: "1 L recarga",
    unit: "recarga",
    packQuantity: 1,
    price: 2800,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: true,
    noceraProduct: true,
    image: "/images/nocera-nn.png",
    updatedAt: "2026-09-19"
  },
  {
    id: "001nk",
    code: "001NK",
    name: "Nocera Birra Kolsch",
    description: "Recarga de cerveza Nocera para venta por litro.",
    brand: "Nocera Birra",
    categoryId: "productos-nocera",
    presentation: "1 L recarga",
    unit: "recarga",
    packQuantity: 1,
    price: 2800,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: true,
    image: "/images/nocera-nn.png",
    updatedAt: "2026-09-19"
  },
  {
    id: "001nri",
    code: "001NRI",
    name: "Nocera Birra Red IPA",
    description: "Recarga de cerveza Nocera para venta por litro.",
    brand: "Nocera Birra",
    categoryId: "productos-nocera",
    presentation: "1 L recarga",
    unit: "recarga",
    packQuantity: 1,
    price: 3900,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: true,
    noceraProduct: true,
    image: "/images/nocera-nn.png",
    updatedAt: "2026-09-19"
  },
  {
    id: "011a",
    code: "011A",
    name: "Agua Cimes",
    description: "Pack de agua para compra mayorista o reposicion comercial.",
    brand: "Cimes",
    categoryId: "aguas-jugos-sodas",
    presentation: "2 L x 6",
    unit: "pack",
    packQuantity: 6,
    price: 3650,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "013ac",
    code: "013AC",
    name: "Agua Villa Manaos",
    description: "Pack de botellas chicas para venta y consumo frecuente.",
    brand: "Villa Manaos",
    categoryId: "aguas-jugos-sodas",
    presentation: "600 cc x 12",
    unit: "pack",
    packQuantity: 12,
    price: 4500,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "002e",
    code: "002E",
    name: "Coca Cola",
    description: "Pack de gaseosa en presentacion familiar.",
    brand: "Coca Cola",
    categoryId: "gaseosas",
    presentation: "1.5 L x 8",
    unit: "pack",
    packQuantity: 8,
    price: 27100,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "001bh",
    code: "001BH",
    name: "Heineken laton",
    description: "Pack cerrado de latas para abastecimiento comercial.",
    brand: "Heineken",
    categoryId: "cervezas",
    presentation: "x 24 unidades",
    unit: "pack",
    packQuantity: 24,
    price: 75900,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "017",
    code: "017",
    name: "Fernet Branca",
    description: "Botella individual de aperitivo.",
    brand: "Branca",
    categoryId: "licores-aperitivos-whisky",
    presentation: "750 cc",
    unit: "botella",
    packQuantity: 1,
    price: 17500,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "121g",
    code: "121G",
    name: "Queso cremoso El Gauchito",
    description: "Producto de fiambreria con precio por kilogramo.",
    brand: "El Gauchito",
    categoryId: "fiambreria",
    presentation: "precio por kg",
    unit: "kg",
    packQuantity: null,
    price: 6438.27,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  },
  {
    id: "032bm",
    code: "032BM",
    name: "Buenos Aires Malbec",
    description: "Botella individual de vino tinto.",
    brand: "Buenos Aires",
    categoryId: "vinos-champagnes",
    presentation: "750 ml",
    unit: "botella",
    packQuantity: 1,
    price: 2200,
    promotionalPrice: null,
    promotionStartsAt: null,
    promotionEndsAt: null,
    available: true,
    active: true,
    featured: false,
    noceraProduct: false,
    image: null,
    updatedAt: "2026-09-19"
  }
];

export const featuredProducts = products.filter((product) => product.featured);
export const noceraProducts = products.filter((product) => product.noceraProduct);
